name: Publish Chronos.Timer.Core to Nuget.Org

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    name: Restore, Build & Publish
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Publish Core Package
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: ${{ github.workspace }}/src/Core/Chronos.Timer.Core.csproj
          # NuGet package id, used for version detection & defaults to project name
          PACKAGE_NAME: Chronos.Timer.Core
          # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
          VERSION_FILE_PATH: ${{ github.workspace }}/src/Core/version.txt
